#
# This file was created by Xilinx Vitis tool.
#


#
# tools
#

RM = rm -f
RMDIR = rm -rf

#
# variables
#

SDCARD_GEN = sdcard_gen
GENERATE_BIF = ::scw::generate_bif

XPFM_PATH = C:/temp/BOOT_CHECK/vitis/design_1_wrapper/export/design_1_wrapper/design_1_wrapper.xpfm
SYS_CONFIG = design_1_wrapper
DOMAINS = standalone_domain
BIF_PATH = C:/temp/BOOT_CHECK/vitis/BOOT_CHECK2_system/Debug/system.bif

BITSTREAM_PATH = C:/temp/BOOT_CHECK/vitis/BOOT_CHECK2/_ide/bitstream/design_1_wrapper.bit
SD_FILES = --elf C:/temp/BOOT_CHECK/vitis/BOOT_CHECK2/Debug/BOOT_CHECK2.elf,psu_cortexa53_0

#
# primary build targets
#

all: sd_card

sd_card:
	-@echo Generating bif file for the system project
	generate_system_bif.bat 59455 ${XPFM_PATH} ${DOMAINS} ${BIF_PATH}
	${SDCARD_GEN} --xpfm ${XPFM_PATH} --sys_config ${SYS_CONFIG} --bif ${BIF_PATH} --bitstream ${BITSTREAM_PATH} ${SD_FILES}

clean:
	$(RMDIR) ./_sds
	${RMDIR} sd_card
	${RM} system.bif

.PHONY: all sd_card clean


